-- Stop TransferGroup, RuleRun and RuleApplication counting.
--
-- These three were the last `autoincrement()` int primary keys, and RuleRun's
-- shows up in a URL (`/rules/runs/9`). Scoping already means a guessed id
-- returns nothing rather than someone else's row — this removes the thing there
-- is to guess, and stops the id itself publishing how many transfers and rule
-- runs exist across every workspace on the instance.
--
-- Two halves, and the second is the one that matters:
--
--   1. The type change. Prisma's own diff stops here — but `SET DATA TYPE TEXT`
--      merely casts 1, 2, 3 into '1', '2', '3'. New rows would get cuids while
--      every existing row stayed a counter, which is most of the problem intact.
--
--   2. Re-keying the existing rows onto opaque ids. The foreign keys are
--      ON UPDATE CASCADE, so updating a parent's id carries its children along
--      and referential integrity is never broken — no dropping and recreating
--      constraints, no window where a leg points at nothing.
--
-- The backfilled ids are random hex from `gen_random_uuid()`, not cuids: cuids
-- are generated by the application and Postgres has no way to make one. They
-- serve the same purpose (opaque, unique, unguessable) and nothing parses these
-- ids, so the mixed format is invisible. New rows get real cuids from Prisma's
-- `@default(cuid())`.

-- 1. The type change (Prisma's DDL).
ALTER TABLE "RuleApplication" DROP CONSTRAINT "RuleApplication_runId_fkey";
ALTER TABLE "Transaction" DROP CONSTRAINT "Transaction_transferGroupId_fkey";

ALTER TABLE "RuleApplication" DROP CONSTRAINT "RuleApplication_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE TEXT,
ALTER COLUMN "runId" SET DATA TYPE TEXT,
ADD CONSTRAINT "RuleApplication_pkey" PRIMARY KEY ("id");
DROP SEQUENCE "RuleApplication_id_seq";

ALTER TABLE "RuleRun" DROP CONSTRAINT "RuleRun_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE TEXT,
ADD CONSTRAINT "RuleRun_pkey" PRIMARY KEY ("id");
DROP SEQUENCE "RuleRun_id_seq";

ALTER TABLE "Transaction" ALTER COLUMN "transferGroupId" SET DATA TYPE TEXT;

ALTER TABLE "TransferGroup" DROP CONSTRAINT "TransferGroup_pkey",
ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "id" SET DATA TYPE TEXT,
ADD CONSTRAINT "TransferGroup_pkey" PRIMARY KEY ("id");
DROP SEQUENCE "TransferGroup_id_seq";

ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_transferGroupId_fkey" FOREIGN KEY ("transferGroupId") REFERENCES "TransferGroup"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "RuleApplication" ADD CONSTRAINT "RuleApplication_runId_fkey" FOREIGN KEY ("runId") REFERENCES "RuleRun"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- 2. Re-key the existing rows off their counters. The FKs above are
-- ON UPDATE CASCADE, so `Transaction.transferGroupId` and
-- `RuleApplication.runId` follow their parents automatically.
UPDATE "TransferGroup" SET "id" = replace(gen_random_uuid()::text, '-', '');
UPDATE "RuleRun" SET "id" = replace(gen_random_uuid()::text, '-', '');
UPDATE "RuleApplication" SET "id" = replace(gen_random_uuid()::text, '-', '');
